#!/usr/bin/perl

use strict;
use warnings;
use bigint;

use Archive::Eubar;

usage() if @ARGV < 2;

my $base = shift;
my $ar = Archive::Eubar->new($base);

my $err = 1;
my %want = map { $_ => 1 } @ARGV;

foreach my $f (@ARGV) {
    my $arf = $ar->find($f);
    $err++, print(STDERR "Can't find: $f\n"), next if !$arf;
    if ($arf->type =~ /^[fl]$/) {
        printf "%9d %9d %s\n", $arf->position, $arf->size, $f;
    }
    else {
        printf "%9s %9s %s\n", qw(- -), $f;
    }
}

exit $err if $err > 1;
