#!/usr/bin/perl

use strict;
use warnings;

use Archive::Eubar;
use Getopt::Long
    qw(:config posix_default gnu_compat require_order bundling no_ignore_case);

sub usage;

my %oktype = map { $_ => 1 } qw(f);
GetOptions(
    'l' => sub { $oktype{'l'} = 1 },
) or usage;
usage if @ARGV < 1;

my $base = shift;
my $ar = Archive::Eubar->new($base);

if (@ARGV && $ARGV[0] =~ /^[@](\d+)$/) {
    die "Fast-forwarding not yet implemented";
}

foreach (@ARGV) {
    my $file = $ar->find($_) or next;
    print(STDERR "Not a plain file: $_\n"), next
        if !$oktype{$file->type};
    $ar->extract($file, \*STDOUT)
        or die "Can't extract ", $file->path;
}

